<a href="https://colab.research.google.com/github/aaasif04/exposys-assignment/blob/master/Exposys_Data_Labs_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [ ]:
data = open('identify_que_category_dataset.txt').read()
data_new = data.lower().split('\n')

how did serfdom develop in and then leave russia ? # unknown


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data_new)
# print((tokenizer.word_index))
total_words = len(tokenizer.word_index)+1

{'what': 1, 'the': 2, 'who': 3, 'is': 4, 'of': 5, 'in': 6, 'unknown': 7, 'was': 8, 'a': 9, 'when': 10, "'s": 11, 'to': 12, 'how': 13, "''": 14, 'for': 15, 'and': 16, 'affirmation': 17, 'did': 18, 'are': 19, 'does': 20, 'on': 21, 'do': 22, 'first': 23, 'name': 24, 'i': 25, 'can': 26, 'where': 27, 'many': 28, 'it': 29, 'from': 30, 'you': 31, 'this': 32, 'with': 33, 'world': 34, 'that': 35, 'be': 36, 'most': 37, 'which': 38, 'as': 39, 'has': 40, 's': 41, 'city': 42, 'u': 43, 'have': 44, 'president': 45, 'country': 46, 'were': 47, 'there': 48, 'get': 49, 'people': 50, 'american': 51, 'find': 52, 'an': 53, 'work': 54, 'his': 55, 'invented': 56, 'by': 57, "'": 58, 'year': 59, 'mean': 60, 'wrote': 61, 'game': 62, 'new': 63, 'called': 64, 'made': 65, 'why': 66, 'state': 67, 'used': 68, 'man': 69, 'time': 70, 'two': 71, 'star': 72, 'at': 73, 'largest': 74, 'movie': 75, 'only': 76, 'known': 77, 'war': 78, 'will': 79, 'fear': 80, 'word': 81, 'he': 82, 'played': 83, '1': 84, 'day': 85, 'company': 

In [ ]:
seq = tokenizer.texts_to_sequences(data_new)
# print(seq)

[[13, 18, 1177, 1178, 6, 16, 632, 306, 404, 7], [1, 307, 1179, 2, 137, 633, 1180, 1], [13, 26, 25, 52, 9, 405, 5, 1181, 58, 406, 154, 7], [1, 1182, 1183, 2, 1184, 123, 2, 634, 59, 5, 2, 1185, 1], [1, 4, 2, 407, 308, 5, 184, 1], [1, 635, 636, 309, 2, 408, 30, 101, 637, 1], [1, 234, 18, 155, 11, 235, 409, 638, 124, 1], [1, 4, 2, 236, 410, 1], [1, 19, 639, 1186, 1], [24, 2, 1187, 640, 641, 1188, 5, 2, 138, 237, 7], [10, 8, 1189, 1190, 112, 10], [66, 22, 1191, 642, 411, 1192, 1193, 7], [3, 8, 2, 1194, 5, 2, 643, 3], [3, 102, 1195, 3], [1, 4, 238, 2, 1196, 1197, 2, 1198, 1199, 40, 185, 640, 1], [1, 1200, 43, 41, 67, 412, 2, 37, 1201, 1], [1, 18, 2, 76, 1202, 310, 12, 2, 43, 41, 413, 644, 33, 1], [13, 28, 1203, 47, 645, 6, 1204, 1205, 139, 1206, 7], [1, 4, 1207, 414, 1208, 14, 1], [1, 4, 53, 1209, 1210, 1], [1, 4, 2, 311, 5, 415, 85, 1], [1, 646, 5, 647, 19, 1211, 6, 648, 1], [24, 649, 113, 1212, 7], [1, 11, 2, 186, 650, 1], [1, 4, 2, 114, 5, 2, 24, 1213, 58, 1], [1, 11, 2, 239, 37, 68, 1214

In [ ]:
padded = pad_sequences(seq)
# print(padded)
# print('***********')
padded_fin = np.array(padded)
# print(padded_fin)

[[   0    0    0 ...  306  404    7]
 [   0    0    0 ...  633 1180    1]
 [   0    0    0 ...  406  154    7]
 ...
 [   0    0    0 ...   44  129   17]
 [   0    0    0 ...    6  391   17]
 [   0    0    0 ...  981 3676   17]]
***********
[[   0    0    0 ...  306  404    7]
 [   0    0    0 ...  633 1180    1]
 [   0    0    0 ...  406  154    7]
 ...
 [   0    0    0 ...   44  129   17]
 [   0    0    0 ...    6  391   17]
 [   0    0    0 ...  981 3676   17]]


In [ ]:
predictors, label = padded_fin[:,:-1],padded_fin[:,-1]
# print(label[8])

1


In [ ]:
max_length = max(len(x) for x in predictors)

In [ ]:
import tensorflow.keras.utils as ku

In [ ]:
labels = ku.to_categorical(label, num_classes=total_words)

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(total_words, 64, input_length=max_length-1))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(20)))
model.add(tf.keras.layers.Dense(total_words, activation='softmax'))

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 29, 64)            235328    
_________________________________________________________________
bidirectional_2 (Bidirection (None, 40)                13600     
_________________________________________________________________
dense_2 (Dense)              (None, 3677)              150757    
Total params: 399,685
Trainable params: 399,685
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = model.fit(predictors, labels, epochs=500, verbose=1)

Epoch 1/500
47/47 [==============================] - 0s 9ms/step - loss: 7.3443 - accuracy: 0.3810
Epoch 2/500
47/47 [==============================] - 0s 9ms/step - loss: 3.0501 - accuracy: 0.4107
Epoch 3/500
47/47 [==============================] - 0s 9ms/step - loss: 1.5195 - accuracy: 0.4107
Epoch 4/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4469 - accuracy: 0.4107
Epoch 5/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4277 - accuracy: 0.4107
Epoch 6/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4203 - accuracy: 0.4107
Epoch 7/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4133 - accuracy: 0.4107
Epoch 8/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4104 - accuracy: 0.4107
Epoch 9/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4083 - accuracy: 0.4107
Epoch 10/500
47/47 [==============================] - 0s 9ms/step - loss: 1.4037 - accuracy: 0.4107
Epoch 11/

output prediction for a raw text
raw sentence shouuld be given to sentence_to_check variable down

In [ ]:
#output prediction check
sentence_to_ckeck = 'what is your name ?'
new_corpus = sentence_to_ckeck.lower()
print(new_corpus)
new_sent_seq = tokenizer.texts_to_sequences([new_corpus])[0]
# print(new_sent_seq)
pad_new = pad_sequences([new_sent_seq], maxlen=max_length, padding='pre')
# print(pad_new)
predicted = model.predict_classes(pad_new, verbose=0)
# print(predicted)

for word, index in tokenizer.word_index.items():
  if index == predicted:
    outt = word
    break

print(outt)

what is your name ?
[1, 4, 94, 24]
